### ISSUE TITLE
Migration to Python3

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#246]
Python 2 is in serios-bugfixes-only mode, python 3 is stable for a few years now. We need to run on version 3 eventually. This task will probably be the next big task after Exaile 4.0 is released with #3 being fixed.

# 1. Preparation:
Make sure all required libraries are available for Python 3.

- [x] migrate remaining dependencies. See [this wiki page](https://github.com/exaile/exaile/wiki/Python3-dependencies-migration-tasklist)
  - [x] most dependencies are available for python 3
  - [x] port to mox3 #244 
  - [x] [port to beautifulsoup4](http://www.crummy.com/software/BeautifulSoup/bs4/doc/#porting-code-to-bs4)
  - [x] make sure musicbrainzngs is available (on arch and other distros?)
  - [x] Clean up python code (see #371)
  - [ ] CDDB. This is an optional dependency for the plugin `cd`, so nothing important enough to block migration. See #608 for a nice way out.
  - [ ] spydaap. This is a dependency of the daapserver/daapclient plugin, see [egh/spydaap](https://github.com/egh/spydaap) or – in case they don't accept our patches – [exaile/spydaap](https://github.com/exaile/spydaap)
  - [x] pyHook

# 2. Convert Exaile source code

- [ ] See the official howto guide: https://docs.python.org/3/howto/pyporting.html
  - [x] #243 
  - [ ] ~#245~
  - [x] include changes from #289
  - [ ] include changes from #171
  - [x] replace sgmllib by HTMLParser or htmllib
  - [ ] use all remaining `__future__` statements in every source file
    - [ ] `absolute_import` (mostly in `plugins/` dir)
    - [ ] `division` (partially done as of 2017-08-01)
    - [ ] `print_function` (mostly done as of 2017-08-01)
    - [ ] `unicode_literals` (this is the hardest part)
  - [ ] `2to3` and other tools
  - [ ] after running `2to3`, start exaile with `python -3` to enable warnings and fix all the remaining bugs
  - [ ] Many, many small fixes
  - [x] update bsddb bindings (bsddb has been removed from python3), otherwise collection database can't be loaded. We need to have proper migration code for this case or use bsddb3 and open the shelf with `shelve.BsdDbShelf(bsddb3.hashopen(...))`.
    - See #399
  - …

__Note__: in an earlier version, I suggested to make the code run with both Python 2 and 3. @sjohannes and @virtuald voted against this, and I agree, especially since we are quite late on the Python 3 train.

**Comment by sjohannes** [comment]
I think supporting Python 2 and 3 at the same time will be more trouble than it's worth; it makes the code ugly and complicates development/testing. If we can get all the dependencies sorted out (including on Windows), in my opinion it's fine to ignore Python 2.

**Comment by virtuald** [comment]
At this point I agree.

**Comment by sjohannes** [comment]
As far as I know distros aren't dropping Python 2 yet, just not installing it by default. That's fine as long as it's still in the repositories.

As for an update on this issue: we can't really start working on this until Exaile 4 is released. Exaile 3 uses PyGTK, which only works on Python 2, so we have to finish the whole migration to PyGObject first. It's been slow because that's also tied to the move to GTK+ 3 and GStreamer 1.

**Comment by leigh123linux** [comment]
RHEL8 will be python3 only.

**Comment by dangmai** [comment]
Is there confirmation somewhere that RHEL8 will not have python2 in the repo? It seems that they'll remove it from the default installation in favor of python3, but I haven't seen indications that python2 will be gone period.

**Comment by Qwerty-Space** [comment]
Any update on this?  Python 2 is being retired soon.  
https://pythonclock.org/

**Comment by virtuald** [comment]
Need to push 4.0 out the door first. It's... there, but we're bad at actually freezing and pushing apparently.

**Comment by Qwerty-Space** [comment]
Oh lol
Fair enough

**Comment by leigh123linux** [comment]
Exaile is likely to be dropped for F32 due to python2 policy.
I don't have the time to jump through FESCO hoops to keep this package (and it's deps) alive that I don't use personally.

https://bugzilla.redhat.com/show_bug.cgi?id=1737955

**Comment by leigh123linux** [comment]
> Exaile is likely to be dropped for F32 due to python2 policy.
> I don't have the time to jump through FESCO hoops to keep this package (and it's deps) alive.
Some of the deps are now orphans so it's time for me to dump exaile.
@genodeftest  I have transferred ownership to you, feel free to orphan. 


> 
> https://bugzilla.redhat.com/show_bug.cgi?id=1737955

**Comment by raveit65** [comment]
I have to drop exaile from Mate-Compiz spin for fedora 32, to fix deployment of the spin.
https://koji.fedoraproject.org/koji/getfile?taskID=39383991&volume=DEFAULT&name=livemedia-out.log&offset=-4000
Do i have to search for another audio-player as replacement, maybe rhythmbox?

**Comment by virtuald** [comment]
... this is done, right?

**Comment by sjohannes** [comment]
Yeah....
